# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - jobsite-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test backend
        run: |
          cd backend
          npm install
          npm run build --if-present
          #npm run test --if-present

      - name: npm install, build, and test frontend
        run: |
          cd frontend
          npm install
          npm run build --if-present
          #npm run test --if-present
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: backend

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: frontend-app
          path: frontend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-app

      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DC48975314FD416CAC7BBAE38CB19194 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_63B14B2F6C9F4C688B163C47046B2896 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1B4FEC030B2843AE9266116F436B0E78 }}

      - name: Deploy backend to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'jobsite-backend'  # Ensure this matches your Azure App Service for the backend
          slot-name: 'Production'
          package: 'backend'

      - name: Deploy frontend to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'jobsite-frontend'  # Ensure this matches your Azure App Service for the frontend
          slot-name: 'Production'
          package: 'frontend'
